name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run GraphQL diagnostics
        run: pnpm gql:check

      - name: Build project
        env:
          TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: pnpm build
